notifications:
  email: false
  slack: mysociety:1M2CXeMwHIf8SrGoKyZrz0jO

language: perl
perl:
  - "5.14" # wheezy, precise
  - "5.18" # trusty
  - "5.20" # jessie
  - "5.22" # xenial
  - "5.24" # stretch, zesty

env:
  global:
    - "S3_BUCKET=fixmystreet-bundle-cache"
    - secure: UjYK8ZJj+5PzbVhzEH1op13Vj0TUNRXER2/TZt5fh8qRTrrFBmXT+XaYcwVXsfUitqa29QE1Hry25Wu+/f8QsTPRKcG0bZ90QcYHnO4ACQssBwaH5Jh4OItDn+3BfroM0Jwxo4hVGBDJcDB8vj2Lzra4ff4jq1Nx6oa9I9CFPPKnD47JbsmxG+3zYGf/FNihubK5x69r1PO6oLZw395arRmyttuCJ1PCLArDwwnJlHuUXebOUF+bjLshbsOEib/1VOd1D+eM+YkFF5iTUlnYSs7hZLYMMiaVr/oxI7xKoxn52AvDs+gOpWVT62Dg6sEac5hzfLdNvTEYCeQy21TlddxcG0mQCZWUrO5KFr72BIOD77Yzhd7BgBihrAR4zVxnlBd6jc0Uzfxn2+9AmB/ymrnruhpw0UVJihky8D6vi3SRQjK/FNLmWvPOTAiYL1ZzYLjElUn3fJr1kwrteOBTlyAAaKRcKNJ5R14zY8Cq/nTHTEGUpiDycua4CHYyoF8wHq9SoBN5gngWGMa8TC/DAtuKq3ozCOFeYOGk/yRhM+0587lWyzI/dMjkLQU/d7JtboQl8+Zf2O3k4ORy2vMUgn6omjcPqpAtH5LyI0pMlyQZXDpypDVZjJJMwgvDVZvCJ3WtTkDYq8W2Xw4ok3hju8upGTU1ZoKWriFbwzwXPzs=
    - secure: fE64wFyh3gHX6HNgkXBbhhTOiHsSStumxVIYCHVsM2ieqfkJDzgyvvLNjEKAXozKiJyBzKtDykqlZTf5g9ziC5FL5yjhdo/gZjQ8FcfAoIn4pnmXEYfVKQk21/+V0HZDxLQCo7DqR365llHe7BgwPK6JCzUu9wtcB27oAFeYXNfDmDj9YowIxRi7pIsuMHdnwzkuydcpJ5cmnQoF5DQaducFtx4cQFigUmdnUQWmMBdJRGS9U6gmPuWUWNICBiXwabzzcatZzDyqnktkMg7gXeLOwVq7LTjMNRLA6w6xNzBw4Ie3PyW4fL7nmSkk4l8yGYIVq4V6JWwo9kypnqrxYGZ3jxA8bPdyXT0tbQvXDLB9gJwxCqQuWZV/Z9+pzKnvuIBicB3qFWxeGcR1hPgAjOmMoWLz2FOCk+1dwlTfFwK9wn/equRErk+a5hIxZcU2GdGBridZQwUe/6j5S1oWHa6mX6XGuybycDna8QcudBWLPt6FuLZnWexbH+3/YS+dBQEU5U/DV1VbmwD0Zht8QEqcFeR9oECw8u7nQb0qOo3U/8Pe5uvHL87rEWHEraA3tJtDlGPtInbWJzw2Y9Xqsqj7yCuinLPj8WfWLWQOe9SxYL1XCnFBA3Jg7TCQeQlmBuNctIt8O+f8ll5/JX3d/LwywGlMWjtI+6Lp25Y+uac=

sudo: false

install:
  - .travis/install
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then cpanm --quiet --notest Devel::Cover::Report::Codecov; fi'
before_script:
  - cp conf/general.yml-example conf/general.yml
  - cp conf/council-banes_confirm.yml-example conf/council-banes_confirm.yml
  - cp conf/council-buckinghamshire_confirm.yml-example conf/council-buckinghamshire_confirm.yml
  - cp conf/council-hounslow_confirm.yml-example conf/council-hounslow_confirm.yml
  - cp conf/council-essex_confirm.yml-example conf/council-essex_confirm.yml
  - cp conf/council-lincolnshire_confirm.yml-example conf/council-lincolnshire_confirm.yml
  - cp conf/council-northamptonshire_alloy.yml-example conf/council-northamptonshire_alloy.yml
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then export HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local/lib/perl5,^t"; fi'
script:
  - script/test
after_script:
  - .travis/after_script
  - 'if [ "$TRAVIS_PERL_VERSION" = "5.24" ]; then cover --report codecov; fi'
